version: '3'
services:
  mariadb2:
    image: mariadb
    container_name: CpuDb-Test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CpuDb-Test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
      
  mariadb:
    image: mariadb
    container_name: CpuDb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CpuDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

    