@url = http://localhost:5239/api
@id = 8a2526c4-e6a6-462e-b783-f4a08a1b3bce

GET {{url}}/home

###

GET {{url}}/processor
Content-type: application/json

{
}

###

GET {{url}}/processor
Content-type: application/json

{
    "manufacturer": "intel",
    "cores": 8
}

###

GET {{url}}/processor
Content-type: application/json

{
    "manufacturer": "amd",
    "socket": "Socket AM5"
}

###

POST {{url}}/processor/create
Content-type: application/json

{
    "manufacturer": "intel",
    "model": "i5-13600k",
    "cores": 14,
    "clockRate": "5.1GHz",
    "socket": "Socket 1700",
    "price": 1549
}

###

GET {{url}}/processor/{{id}}

###

PATCH {{url}}/processor/{{id}}
Content-Type: application/json

{
    "price": 1600
}

###

PUT {{url}}/processor/{{id}}
Content-Type: application/json

{
    "cores": 14,
    "price": 1549,
    "model": "i5-13600"
}

###

DELETE {{url}}/processor/{{id}}