@url = http://localhost:5239/api
@id = 348a6a29-eac2-4fee-b714-0bf79606cfd6

GET {{url}}/home

###

GET {{url}}/processor

###

GET {{url}}/processor
    ?manufacturer=intel
    &cores=8

###

GET {{url}}/processor
    ?manufacturer=amd
    &socket=Socket%20AM5


###

GET {{url}}/processor
Content-type: application/json

{
    "model": "i9-11900k"
}

###

POST {{url}}/processor/create
Content-type: application/json

{
    "manufacturer": "intel",
    "model": "i5-13600k",
    "cores": 14,
    "clockRate": "5.1GHz",
    "socket": "Socket 1700",
    "price": 1549
}

###

GET {{url}}/processor/{{id}}

###

PATCH {{url}}/processor/{{id}}
Content-Type: application/json

{
    "price": 1600
}

###

PUT {{url}}/processor/{{id}}
Content-Type: application/json

{
    "cores": 14,
    "price": 1549,
    "model": "i5-13600"
}

###

DELETE {{url}}/processor/{{id}}